### ISSUE TITLE
Ignore commented YT channels

### ISSUE THREAD

**Issue by bohning** [bohning/usdb_syncer#115]
If a comment contains an entire user/channel (e.g. http://www.youtube.com/user/eurovision) or even a search query (e.g. https://www.youtube.com/results?search_query=hit+that), the Syncer will download the entire channel if no meta-tags are present.
The YT regex for valid single song URLs should exclude user/channels.

**Comment by RumovZ** [comment]
20c424752bccb5f12a4f6a1027a0e4e649b9b0af

**Comment by Baklap4** [comment]
Can this be linked to #135  (as in closes when pr is merged?)

**Comment by Baklap4** [comment]
Correct that it is linked in a commit, however it doesn't show up in the issue list. You can link these by using the "Development" on the right of this issue

![image](https://github.com/bohning/usdb_syncer/assets/3918517/115e061f-41c8-4250-af74-75b864e602bd)

See for example #136 
![image](https://github.com/bohning/usdb_syncer/assets/3918517/be46a1e1-c5d6-4687-8a8e-90a647825e53)

![image](https://github.com/bohning/usdb_syncer/assets/3918517/a3914cad-f6b0-4ec6-b645-98b0301921a1)


This way it's faster recognizable which items are already done and which aren't.
Another way to indicate it is to use labels
