### ISSUE TITLE
LinuxPasswordManager error on Archlinux

### ISSUE THREAD

**Issue by barbeque-squared** [bohning/usdb_syncer#136]
Downloaded the 0.1.0 release. I use Archlinux. I'm going to assume I'm missing a package but I don't know which one (and maybe it can also handle this more gracefully?)

```
[bbq@luna bohning]$ chmod +x USDB_Syncer-0.1.0-Linux 
[bbq@luna bohning]$ ./USDB_Syncer-0.1.0-Linux 
Gtk-Message: 14:27:02.969: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:27:02.970: Failed to load module "canberra-gtk-module"

(USDB_Syncer-0.1.0-Linux:3831): dbind-WARNING **: 14:27:02.976: AT-SPI: Error retrieving accessibility bus address: org.a11y.Bus.Error: Failed to execute child process “/usr/bin/dbus-broker-launch” (No such file or directory)

<removed a whole bunch of GTK theme warnings since a lot of programs do that>

2023-05-13 14:27:03 [ERROR] Uncaught exception:
    Traceback (most recent call last):
      File "usdb_syncer/main.py", line 36, in <module>
      File "usdb_syncer/main.py", line 31, in cli_entry
      File "usdb_syncer/gui/mw.py", line 309, in main
      File "usdb_syncer/gui/mw.py", line 318, in _load_main_window
      File "usdb_syncer/song_list_fetcher.py", line 23, in get_all_song_data
      File "usdb_syncer/song_list_fetcher.py", line 49, in get_available_songs
      File "usdb_syncer/usdb_scraper.py", line 333, in get_usdb_available_songs
      File "usdb_syncer/usdb_scraper.py", line 231, in get_usdb_page
      File "usdb_syncer/usdb_scraper.py", line 222, in page
      File "usdb_syncer/usdb_scraper.py", line 78, in session
      File "usdb_syncer/usdb_scraper.py", line 64, in new_session_with_cookies
      File "usdb_syncer/settings.py", line 224, in cookies
      File "browser_cookie3/__init__.py", line 973, in chrome
      File "browser_cookie3/__init__.py", line 516, in __init__
      File "browser_cookie3/__init__.py", line 331, in __init__
      File "browser_cookie3/__init__.py", line 344, in __add_key_and_cookie_file
      File "browser_cookie3/__init__.py", line 238, in get_password
    TypeError: _LinuxPasswordManager.__get_kdewallet_password_jeepney() missing 1 required positional argument: 'key'
[3831] Failed to execute script 'main' due to unhandled exception!
```

**Comment by RumovZ** [comment]
@mjhalwa, I know you were running on WSL before. Did you manage to make it work with a recent version?

**Comment by mjhalwa** [comment]
i tried it some month ago, i guess it is not compareable to todays version, but i could give it a try over the weekend. Seems I could also try it directly in arch linux: https://www.bleepingcomputer.com/news/microsoft/arch-linux-for-wsl-is-now-available-in-the-microsoft-store/

**Comment by mjhalwa** [comment]
started by running Release 0.1.0 on Ubuntu 23.04 and ran straight into #137. It seems there is one or are multiple issues with Qt on Linux (distributions), that we have to have a closer look at. I will focus on #137 first and then come back to this issue.

Note: I started with Ubuntu as it seemed we have issues with Linux distributions in general and I hoped I can reproduce the error on Ubuntu too - The installation guide of Arch Linux seems to involve several steps and was therefore less straight forward for me.

**Comment by mjhalwa** [comment]
Trying to debug this with a clone of `main` branch in a `venv` (**currently not the Linux Release**)

I had a look into `browser_cookie3/__init__.py`. As we seem to have this Issue on Linux-distros it has to be something Linux specific. Thus these lines at the very beginning seem interesting:

```
if sys.platform.startswith('linux') or 'bsd' in sys.platform.lower():
    try:
        import dbus
        USE_DBUS_LINUX = True
    except ImportError:
        import jeepney
        from jeepney.io.blocking import open_dbus_connection
        USE_DBUS_LINUX = False
```

I could validate in a `venv` on Ubuntu 23.04 that `import dbus` fails with an `ImportError` so probably the corresponding Package for `dbus` is missing. Some googeling lead me to https://stackoverflow.com/questions/37521162/how-solve-importerror-no-module-named-dbus where several answers indicate to install a Python-Package called `python-dbus`. But I was only able to find a Package [`dbus-python`](https://pypi.org/project/dbus-python/), which fails on `pip install dbus-python` with

```
error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      + meson setup /tmp/pip-install-qu0aib6v/dbus-python_29cd51f5f88e475099d0e291521385fd /tmp/pip-install-qu0aib6v/dbus-python_29cd51f5f88e475099d0e291521385fd/.mesonpy-4agvacuo/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-qu0aib6v/dbus-python_29cd51f5f88e475099d0e291521385fd/.mesonpy-4agvacuo/build/meson-python-native-file.ini
      The Meson build system
      Version: 1.1.0
      Source dir: /tmp/pip-install-qu0aib6v/dbus-python_29cd51f5f88e475099d0e291521385fd
      Build dir: /tmp/pip-install-qu0aib6v/dbus-python_29cd51f5f88e475099d0e291521385fd/.mesonpy-4agvacuo/build
      Build type: native build
      Project name: dbus-python
      Project version: 1.3.2
      
      ../../meson.build:4:0: ERROR: Unknown compiler(s): [['cc'], ['gcc'], ['clang'], ['nvc'], ['pgcc'], ['icc'], ['icx']]
      The following exception(s) were encountered:
      Running `cc --version` gave "[Errno 2] No such file or directory: 'cc'"
      Running `gcc --version` gave "[Errno 2] No such file or directory: 'gcc'"
      Running `clang --version` gave "[Errno 2] No such file or directory: 'clang'"
      Running `nvc --version` gave "[Errno 2] No such file or directory: 'nvc'"
      Running `pgcc --version` gave "[Errno 2] No such file or directory: 'pgcc'"
      Running `icc --version` gave "[Errno 2] No such file or directory: 'icc'"
      Running `icx --version` gave "[Errno 2] No such file or directory: 'icx'"
      
      A full log can be found at /tmp/pip-install-qu0aib6v/dbus-python_29cd51f5f88e475099d0e291521385fd/.mesonpy-4agvacuo/build/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

So I installed

```
sudo apt install gcc
```

and a re-run gives me

```
rogram python found: YES (/home/ubuntu/git/usdb_syncer/venv/bin/python3)
      Dependency dbus-1 found: YES 1.14.4 (cached)
      Configuring TestSuitePythonService.service using configuration
      Configuring tmp-session-bus.conf using configuration
      Program dbus-run-session found: YES (/usr/bin/dbus-run-session)
      
      ../../test/meson.build:98:15: ERROR: Python dependency not found
      
      A full log can be found at /tmp/pip-install-04vv4ybj/dbus-python_db14bb3c2cc148788be440ee42b81118/.mesonpy-x0s8ax5t/build/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

googeling lead me to https://stackoverflow.com/a/69257467 so I installed

```
sudo apt install python3-dev
```

then pip install (in venv) succeeded

```
pip install dbus-python
```

Then I run `usdb_syncer` and a Prompt asks me for a Password for a "new keyring". After entering some Password the GUI loads

Note: This does not resolve the issue with the Release version, I guess because `dbus-python`-Dependency is missing. @g3n35i5 could you please try to build a new release including dbus-python in `setup.cfg` (together with #137 on an older Ubuntu Version) to see if this fixes #136 and #137?

**Comment by mjhalwa** [comment]
after endless trials, I guess I got it to work and I have a linux release with the additional package:

https://github.com/mjhalwa/usdb_syncer/releases/tag/0.1.18

@barbeque-squared may you try this linux release (forget the version number its just a place holder, also it does not contain a songlist already)

**Comment by barbeque-squared** [comment]
@mjhalwa this is definitely a big improvement!

```
[bbq@luna bohning]$ ./USDB_Syncer-0.1.18-Linux 
Gtk-Message: 16:03:25.838: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:03:25.838: Failed to load module "canberra-gtk-module"

(USDB_Syncer-0.1.18-Linux:4036): dbind-WARNING **: 16:03:25.844: AT-SPI: Error retrieving accessibility bus address: org.a11y.Bus.Error: Failed to execute child process “/usr/bin/dbus-broker-launch” (No such file or directory)

<removed a whole bunch of GTK theme warnings since a lot of programs do that>

2023-05-26 16:03:25 [DEBUG] Failed to retrieve Chrome cookies.
2023-05-26 16:03:25 [DEBUG] Starting new HTTPS connection (1): usdb.animux.de:443
2023-05-26 16:03:26 [DEBUG] https://usdb.animux.de:443 "GET /?link=profil HTTP/1.1" 200 None
2023-05-26 16:03:26 [DEBUG] Loading KWallet
2023-05-26 16:03:26 [DEBUG] Loading SecretService
2023-05-26 16:03:26 [DEBUG] Loading Windows
2023-05-26 16:03:26 [DEBUG] Loading chainer
2023-05-26 16:03:26 [DEBUG] Loading libsecret
2023-05-26 16:03:26 [DEBUG] Loading macOS
2023-05-26 16:03:26 [ERROR] Uncaught exception:
    Traceback (most recent call last):
      File "usdb_syncer/main.py", line 36, in <module>
      File "usdb_syncer/main.py", line 31, in cli_entry
      File "usdb_syncer/gui/mw.py", line 399, in main
      File "usdb_syncer/gui/mw.py", line 408, in _load_main_window
      File "usdb_syncer/song_list_fetcher.py", line 23, in get_all_song_data
      File "usdb_syncer/song_list_fetcher.py", line 49, in get_available_songs
      File "usdb_syncer/usdb_scraper.py", line 333, in get_usdb_available_songs
      File "usdb_syncer/usdb_scraper.py", line 231, in get_usdb_page
      File "usdb_syncer/usdb_scraper.py", line 222, in page
      File "usdb_syncer/usdb_scraper.py", line 79, in session
      File "usdb_syncer/usdb_scraper.py", line 49, in establish_usdb_login
      File "usdb_syncer/settings.py", line 31, in get_usdb_auth
      File "keyring/core.py", line 55, in get_password
      File "keyring/backends/fail.py", line 25, in get_password
    keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
[4036] Failed to execute script 'main' due to unhandled exception!
```

The `NoKeyringError` also contains a link to https://pypi.org/project/keyring, which is already tons more useful [compared to the KDE error]. I assume it is not planned to ever make USDB Syncer work without any kind of keyring installed? I'll try and install one regardless and see if maybe they've improved from the session-destroying things they were way back in the day, because unless a plaintext alternative is also in the works, it actually makes sense for USDB Syncer to require one.

If you want to cater to that one Linux user that _doesn't_ know what a terminal is, you might consider catching the `NoKeyringError` and putting the message in a UI box (because right now it's just the splash for a second and then it disappears) but that should probably be its own ticket, and I'm not too fussed about it.

**Comment by RumovZ** [comment]
> I assume it is not planned to ever make USDB Syncer work without any kind of keyring installed?

It's not required because if you're logged in to USDB with your browser, you can reuse that session, too. So it makes sense to catch and log that error instead of aborting.

**Comment by mjhalwa** [comment]
shall we add the `gnome-keyring`-issue to a separate issue or add a "Troubleshooting"-Section to the readme for this package?

**Comment by barbeque-squared** [comment]
To clarify: in the original post, I _did_ already have `python-dbus` installed (as well as libsecret etc), I just did not have an actual backend for opensecrets installed (in my case `gnome-keyring`).
The release linked in https://github.com/bohning/usdb_syncer/issues/136#issuecomment-1563521924 makes it error in a much nicer/more useful way.

Ideally it would actually start _without_ `gnome-keyring` installed, it just disables certain login methods (I'm assuming the `None` method is the one which actually requires it, since the rest just reads some cookies)

**Comment by mjhalwa** [comment]
I found something here: https://github.com/jaraco/keyring/issues/566#issuecomment-1407736677

> [solved](https://github.com/AndreyNikiforov/keyring_test) same/similar issue by using `pyinstaller --collect-all keyrings.alt --hidden-import pkgutil`
