### ISSUE TITLE
pin ubuntu 23.04 in linux build engine

### ISSUE THREAD

**Issue by mjhalwa** [bohning/usdb_syncer#142]
generation of releases is configured in [release.yaml](../blob/main/.github/workflows/release.yaml#L15). Currently linux releases are built with `ubuntu-latest`. The usage of (currently) latest Python version 3.11 requires at least ubuntu 23.04 and thus `glibc` version 2.35. Ubuntu 23.04 is currently the latest release of ubuntu. But soon there will be newer versions. Keeping `ubuntu-latest` in `release.yaml` will further increase the minimum `glibc` version required to run the executable.

[Github - Actions - Available Images](https://github.com/actions/runner-images#available-images) shows the currently available images. `ubuntu-23.04` is not yet available. I recommend to regularly check the available images and when available pin `ubuntu-latest` to `ubuntu-23.04`.

**Comment by RumovZ** [comment]
This does not seem to be correct:
- `ubuntu-latest` is Ubuntu 22.04.
- There is no image for 23.04.
- USDB Syncer runs fine on Ubuntu 22.04 with glibc 2.35.

**Comment by RumovZ** [comment]
Closing. Feel free to reopen if you have new infos.
