### ISSUE TITLE
Missing Cookie support for Chromium

### ISSUE THREAD

**Issue by DerGitRob** [bohning/usdb_syncer#153]
I use Linux and therefore I'm not using chrome, but chromium.
Unfortunately, there is no option for chromium.

Cookies are stored in **~/.config/chromium/** but with option "Chrome" usdb_syncer searches in ~/.config/google-chrome/

Could you please add an option to manually give a path or add Chromium support?

**Comment by bohning** [comment]
<img width="253" alt="image" src="https://github.com/bohning/usdb_syncer/assets/1497707/4e919fd2-ead2-4b56-83be-ff0eb89db003">

**Comment by DerGitRob** [comment]
Oh, sorry. My eyes were too fast or too blind after a stressful day. Thanks for the quick "solution" :)
