### ISSUE TITLE
ffmpeg error `GLIBCXX_3.4.32' not found

### ISSUE THREAD

**Issue by DerGitRob** [bohning/usdb_syncer#154]
running Debian Bookworm

```
2023-08-30 21:08:25 [DEBUG] #26090: Error running command ['/usr/bin/ffmpeg', '-filters']: /usr/bin/ffmpeg: /tmp/_MEIUpfaSQ/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/librubberband.so.2)
/usr/bin/ffmpeg: /tmp/_MEIUpfaSQ/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/libchromaprint.so.1)
```
apt-get install libstdc++6
`libstdc++6 ist schon die neueste Version (13.2.0-2)`

strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.32 | grep GLIBCXX_3.4.32
`GLIBCXX_3.4.32`

but with the given tmp path is missing that lib:
strings /tmp/_MEIUpfaSQ/libstdc++.so.6 | grep GLIBCXX_
```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBCXX_3.4.30
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by DeinAlptraum** [comment]
@DerGitRob What does `ls -l /usr/lib/x86_64-linux-gnu/libstdc++.so` produce? This should be a soft link to `/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.32`. If that link was not updated together with the package at some point, that could produce the error you described.

**Comment by RumovZ** [comment]
Closing. Feel free to reopen if you have new infos.
