### ISSUE TITLE
Slow startup after downloading all the files

### ISSUE THREAD

**Issue by Baklap4** [bohning/usdb_syncer#156]
Heey folks,

I've been testing quite a bit with the new release and i love this project it helps me get the latest and greatest songs which is great!
Thanks for making it!

However starting the application (after downloading all of the songs) takes quite a while with lots of diskactivity.
I'm not quite sure how the loading is done, but i do see a `<songId>.usdb` file in every folder which is probably used for checking the songs during startup?

I'm ussually waiting for 10 to 20 minutes on my harddisk (which isn't throttling during loading) for the gui to popup.
This is quite the wait... this is probably due to having to go through each directory to get the info from these files?
If we can have one overlapping file within the `C:\Users\<user>\AppData\Local\bohning\usdb_syncer\Cache` folder this would immensly speed up the loading

As a side note; during startup a splashscreen is shown, however the splashscreen doesn't have a windows taskbar icon so it's only viewable by minimizing other programs

**Comment by Baklap4** [comment]
It seems the [song_list_fetcher.py](https://github.com/bohning/usdb_syncer/blob/main/src/usdb_syncer/song_list_fetcher.py#L72-L83) retrieves the current locally stored status by traversing each directory and read the `<songId>.usdb` file.

I think this can be optimized by dumping these files into an array at exiting the application and then saved in the cache directory next to `available_songs.json`. Which will then be used during startup which will be significantly faster than traversing each few kb usdb files. This will counter the overhead of opening each individual (small) file.

Shutdown of the application will get a performance hit though as it still has to go through all the directories

**Comment by RumovZ** [comment]
I personally don't have such a large collection that it would matter, but I think @bohning mentioned something similar.
Caching could be a way to improve startup time, but we will have to think about how to invalidate the cache.
Another option would be to launch without information about local files and load that later in the background. That would also help with changing the song folder during runtime, which certainly has the same problem.
