### ISSUE TITLE
Updating and staying up-to-date with latest changes

### ISSUE THREAD

**Issue by Baklap4** [bohning/usdb_syncer#157]
Sometimes songs get updated in USDB. This can be done through adding a comment, updating the txt file and maybe at a later point correctifying through usdb-syncer (#111)

As a user of USDB-Syncer i'd love to be told that a song i have previously downloaded is out of date and needs to be updated.

Currently to achieve the same behavior you'd have to select all the songs you've downloaded and add them to a batch to download again. Sure a lot will be skipped, but those checks need to happen for every song.. this is a major performance concern and not needed if implemented correctly.

One way to deal with this problem is:
- [ ] Add OutOfDate to the localSongs object
- [ ] Determine when a song is out of date
    - [ ] Fetch songs and check when it's last been edited/updated
    - [ ] Check the comments for updates
    - [ ] Execute once (during startup) or on interval (2 hours) to keep the song-list up-to-date
- [ ] Add OutOfDate to the song-list and batch download

**Comment by RumovZ** [comment]
Expanding on my answer on Discord, this can only be done on a song-by-song basis, as the song list does not provide this info. In other words, it's just as expensive as doing a song download, which makes it pointless.
I'm aware that it would be really useful feature, but we can only work with what USDB offers.

**Comment by DerGitRob** [comment]
Maybe an Admin of usdb could help implementing the timestamp of the last update addionally to the create date in usdb itself...

**Comment by bohning** [comment]
As long as it’s not possible to get update infos for individual songs, the idea behind the syncer is to let it run on your song selection say the day (or a few hours, depending on your song collection size) before your next karaoke party. It will then pull all updates (and skip all unchanged files). Since there won’t be too many updates (if you perform this every once in a while), this will only take an hour or two for moderately-sized song collections (skip is < 1 second per song, so a song collection of say 3600 songs should be updated in about an hour).

**Comment by Baklap4** [comment]
For the meantime AnimuxAlex responded

>Asgard Sings! — Today at 12:28 PM
>@AnimuxAlex Would it be possible to add a modified date (of a song) to the list table after searching? (can be hidden if we don't want to actually show it to the end-user)
If yes the usdb-syncer can fairly easy check this date against the locally stored date of a song to determine if it's outdated when we hit the "Synchronize -> Check USDB Song List". This would solve https://github.com/bohning/usdb_syncer/issues/157
This would save a lot of probably pointless calls to each individual songId uri and would make an update way faster than the presumed 1 hour for 3600 songs
>The modified date should be modified and set to now when a song is edited. Optional would be to also update the modified when a comment is posted (for potential new video's).

>AnimuxAlex — Today at 12:30 PM
>Should be possible. I am currently in the middle of rewriting usdb. I will consider it.
>It could also be possible to just query a list of updated songs from the server since a recorded timestamp.

>Asgard Sings! — Today at 12:47 PM
> [AnimuxAlex — Today at 12:30 PM]: Should be possible.
>That'd be supercool for the shortterm! ❤️
> [AnimuxAlex — Today at 12:30 PM]: It could also be possible to just query a list of updated songs from the server since a recorded timestamp.
That'd also solve the problem. USDB-syncer would need to keep in mind what the last synctime was but that's easy enough aswell 🙂
Least invasive would be the extra column in the list table though ^..^!
