### ISSUE TITLE
Easy way to remove local songs downloaded through USDB-Syncer

### ISSUE THREAD

**Issue by Baklap4** [bohning/usdb_syncer#158]
I've recently downloaded the whole library.
I came across 2237 songs which don't have audio so these songs are pretty much unusable (at least for us in Performous)

I'd love to get an extra option in the batch menu to Remove these local files.

The current workaround is to:
1. Sort on Audio
2. Select and add all the songs to the batch which don't have audio
3. Use the `Batch -> Export IDs to file` to Export the batchlist to a file usdb_ids
4. Traverse the whole directory and find the matching id's and delete those folders

```
#!/bin/bash

# File containing the list of IDs
id_file="remove-usdbids.usdb_ids"

# Directory to traverse
search_directory="/mnt/e/Karaoke/USDB\ -\ live"

# Read IDs from the file into an array
mapfile -t ids < "$id_file"

# Use parallel to perform a dry run
dry_run_remove_folder() {
  local id="$1"
  local folder="$2"
  matching_files=$(find "$folder" -type f -name "${id}.usdb")

  if [ -n "$matching_files" ]; then
    echo "Dry run: Removing folder: $folder"
  else
    echo "Dry run: No matching file found for ID $id in $folder"
  fi
}

export -f dry_run_remove_folder
parallel -j4 dry_run_remove_folder {} "$search_directory" ::: "${ids[@]}"

echo "Dry run completed. No folders have been deleted."
```

**Comment by bohning** [comment]
See #31.
