### ISSUE TITLE
VIDEO tag is being parsed even though it's a local file

### ISSUE THREAD

**Issue by Baklap4** [bohning/usdb_syncer#169]
Song: https://usdb.animux.de/?link=detail&id=20403
syncer: latest main
Reproduce:
1. Download the song
2. Restart the syncer
3. [WARNING] #20403: unknown key for meta tag: 'Alessio Bernabei - Io e te = la soluzione.mp4

This is because the parsed `VIDEO` tag in the locally stored txt file contains the `=` character this messes with the metatag extraction part

easy workaround: Change title to not contain the `=` as this is how the video tag gets filled i think

**Comment by mjhalwa** [comment]
I could reproduce on windows on f1058aa .

I had a look to the code to find the exact location this is raised:

1. in [`cli_entry()` of `usdb_syncer/main.py`](https://github.com/bohning/usdb_syncer/blob/f1058aa9959e5b2333e7e8140d8fa1c9eb9c25d3/src/usdb_syncer/main.py#L29-L31) runs `main()` of `usdb_syncer/gui/mw.py`
2. in [`main()` of `usdb_syncer/gui/mw.py`](https://github.com/bohning/usdb_syncer/blob/f1058aa9959e5b2333e7e8140d8fa1c9eb9c25d3/src/usdb_syncer/gui/mw.py#L415) runs `_load_main_window(mw)` in same module
3. in [`_load_main_window(mw: MainWindow)` of `usdb_syncer/gui/mw.py`](https://github.com/bohning/usdb_syncer/blob/f1058aa9959e5b2333e7e8140d8fa1c9eb9c25d3/src/usdb_syncer/gui/mw.py#L424) runs `songs = get_all_song_data(False)` of `usdb_syncer/song_list_fetcher.py`
4. in [`def get_all_song_data(force_reload: bool)` of `usdb_syncer/song_list_fetcher.py`](https://github.com/bohning/usdb_syncer/blob/f1058aa9959e5b2333e7e8140d8fa1c9eb9c25d3/src/usdb_syncer/song_list_fetcher.py#L22) runs `local_files = find_local_files()` in same module
5. in [`find_local_files()` of `usdb_syncer/song_list_fetcher.py`](https://github.com/bohning/usdb_syncer/blob/f1058aa9959e5b2333e7e8140d8fa1c9eb9c25d3/src/usdb_syncer/song_list_fetcher.py#L77) a list of all `path in settings.get_song_dir().glob("**/*.usdb")` is looped and if `meta := SyncMeta.try_from_file(path)` - so if there is a meta tag in the `.usdb`-file - the paths is checked `if txt := _get_song_txt(meta, path.parent)` in the same module
6. in [`_get_song_txt(meta: SyncMeta, folder: Path)` of `usdb_syncer/song_list_fetcher.py`](https://github.com/bohning/usdb_syncer/blob/f1058aa9959e5b2333e7e8140d8fa1c9eb9c25d3/src/usdb_syncer/song_list_fetcher.py#L92) if check `if meta.txt` is true, checks `if txt_path.exists() and (contents := try_read_unknown_encoding(txt_path))` then returns `SongTxt.try_parse(contents, logger)` of `usdb_syncer/song_txt/__init__.py`
7. in [`Songtxt.parse(cls, value: str, logger: Log)` in `usdb_syncer/song_txt/__init__.py`](https://github.com/bohning/usdb_syncer/blob/f1058aa9959e5b2333e7e8140d8fa1c9eb9c25d3/src/usdb_syncer/song_txt/__init__.py#L50) finally parses the meta tags of the local song running `meta_tags = MetaTags.parse(headers.video or "", logger)`
