### ISSUE TITLE
Number of songs to download and progress bar/indicator

### ISSUE THREAD

**Issue by bohning** [bohning/usdb_syncer#17]
If the user downloads many songs, it would be helpful to have some kind of feedback of how many songs are going to be downloaded (and maybe a time estimation?), as well as some kind of progress bar that shows how many songs have already been downloaded and how many more are remaining. One idea is to have a progress bar per song in the song table (e.g. as in JDownloader), but also a global progress bar for the overall download process.

**Comment by mjhalwa** [comment]
I want to share some weblinks, that might be useful to resolve this issue:

[QtDesignStudio - Illustrates how to use timelines to create an animated progress bar.](https://doc.qt.io/qtdesignstudio/qtdesignstudio-progressbar-example.html)
[Stackoverflow - [How to edit stylesheet for QProgressBar](https://stackoverflow.com/questions/72644810/how-to-edit-stylesheet-for-qprogressbar)](https://stackoverflow.com/questions/72644810/how-to-edit-stylesheet-for-qprogressbar)
[Example: RoundProgressBar](https://anjalp.github.io/PySide2extn/pages/examples/rpbExamples)
[Example: SpiralProgressBar](https://anjalp.github.io/PySide2extn/pages/examples/spbExamples)

Personally I think 1 main + number of parallel downloads linear progress bars at the very bottom might look good enough. Progressbars might simply count the stage of the songs with 0% not started and 100% "All done" log. It might be an additional eye catcher to display
- the last downloaded cover image or
- a pile of downloaded cover images or
- all cover images in a rectangular pattern of tiles

Another funky idea:

- a separate download area/tab/sidemenu that displays a light grey square for each song to download,
- while downloading a circular loading bar within the square indicates progress,
- when done displays the cover image (or default-cover image from usdx if cover image is missing).
- Hovering each square might display title and artist.
- When finished with total download, a border around all squares or the background might be colored green
