### ISSUE TITLE
[Filters] Filter songs by release year

### ISSUE THREAD

**Issue by marwin89** [bohning/usdb_syncer#185]
### Suggestion:
It would be cool to filter songs by release year in usdb-syncer.

### Use Case:

- As a User I want to search for songs in a certain year.
- As a User I want to see songs only from this current year.

### Estimation
- Quick Win: low effort, high impact.

**Comment by bohning** [comment]
As long as this information is not provided by the song table of usdb, it is not feasible (or only feasible for songs that you have locally). We already asked for more info columns in the song table on usdb, hopefully this will be available with the overhaul of usdb.

**Comment by marwin89** [comment]
ah alright! do you think alex will update usdb till this years end or next year? did he said something about it?
