### ISSUE TITLE
Use swisscharts song samples as previews in the song table

### ISSUE THREAD

**Issue by bohning** [bohning/usdb_syncer#19]
Not sure if this is possible, but many songs in usdb have a link to a 30 second preview of the song, this could facilitate the song selection process if the user is unsure about a certain song. Since this link is only to be found on the song details page, a kind of background thread would have to crawl all song pages, read out the swisscharts URL and cache them, then insert them in the song table for a preview. Alternatively, swisscharts could be queried by artist/title and the preview URL could be scraped in a background process.

Not sure if this is feasible, but it would be a great feature I think.

**Comment by randompersona1** [comment]
This is implemented.
