### ISSUE TITLE
Installation issue: ModuleNotFoundError: No module named 'usdb_syncer.gui.forms'

### ISSUE THREAD

**Issue by rogerGunis** [bohning/usdb_syncer#191]
Hi,

building and running this app is very hard ... currently I have this problem

`
[07:39:19]> ./USDBSyncer
ERROR:root:Uncaught exception:
    Traceback (most recent call last):
      File "usdb_syncer/main.py", line 66, in <module>
    cli_entry(run_tools=False)
      File "usdb_syncer/main.py", line 56, in cli_entry
    from usdb_syncer.gui.mw import main  # pylint: disable=import-outside-toplevel
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
      File "usdb_syncer/gui/mw.py", line 22, in <module>
    from usdb_syncer.gui.about_dialog import AboutDialog
      File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
      File "usdb_syncer/gui/about_dialog.py", line 7, in <module>
    from usdb_syncer.gui.forms.AboutDialog import Ui_Dialog
    ModuleNotFoundError: No module named 'usdb_syncer.gui.forms'
[185429] Failed to execute script 'main' due to unhandled exception!
`
can anyone help?

Thx in advance
Roger

**Comment by mjhalwa** [comment]
Hi there,

Please provide some more information on your operating system. From your call, I guess you are on some Linux? Building and running on Linux is more difficult, ispecially as non of us develops on Linux. But we try to help out, if we can to provide better support for Linux.

**Comment by rogerGunis** [comment]
ah, ok, thank you for your fast response.
Yes, i'm on linux / wsl2 with debian trixie/sid. Unfortunately I'm a newbie in python stuff...
The app has compiled without problems and after starting the USDBSyncer  in dist directory the error occures. Do I have to set some additional PATH variables for PYTHON to find the app libs?

Thx in advance
Regards
Roger

**Comment by mjhalwa** [comment]
I am sorry, I currently have no time to test this. If I have the opportunity, I can check on a windows 11 with WSL and some ubuntu.

what commit or release did you try to bild / run?

Until then some ideas:

- I remember there might be some issues with GUIs coming from WSL
- have you followed our [installation instructions](https://github.com/bohning/usdb_syncer#development) and used [pipenv](https://pipenv.pypa.io/en/latest/)? Running usdb_syncer then also requires a pipenv shell or pipenv run in order to use a proper enivonment.

**Comment by rogerGunis** [comment]
its on last and on tag 0.3.0 ... I try to setup with windows

**Comment by rogerGunis** [comment]
same on windows

PS F:\wslAccess\usdb_syncer> .\dist\USDBSyncer.exe
ERROR:root:Uncaught exception:
    Traceback (most recent call last):
      File "usdb_syncer\main.py", line 66, in <module>
      File "usdb_syncer\main.py", line 56, in cli_entry
      File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
      File "usdb_syncer\gui\mw.py", line 22, in <module>
      File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
      File "usdb_syncer\gui\about_dialog.py", line 7, in <module>
    ModuleNotFoundError: No module named 'usdb_syncer.gui.forms'
[26788] Failed to execute script 'main' due to unhandled exception!
PS F:\wslAccess\usdb_syncer>

don't get confuesed about the wslAccess directory, its a user Powershell

steps

python -m pip install pipenv --user
pip install pyinstaller
python -m pipenv sync --dev
pyinstaller --name "USDBSyncer" --onefile src/usdb_syncer/main.py


installation trace 


PS F:\wslAccess\usdb_syncer> pyinstaller --name "USDBSyncer" --onefile src/usdb_syncer/main.py
439 INFO: PyInstaller: 6.0.0
439 INFO: Python: 3.11.3
455 INFO: Platform: Windows-10-10.0.22621-SP0
455 INFO: wrote F:\wslAccess\usdb_syncer\USDBSyncer.spec
455 INFO: Extending PYTHONPATH with paths
['F:\\wslAccess\\usdb_syncer\\src']
1239 INFO: checking Analysis
1239 INFO: Building Analysis because Analysis-00.toc is non existent
1239 INFO: Initializing module dependency graph...
1239 INFO: Caching module graph hooks...
1255 INFO: Analyzing base_library.zip ...
2291 INFO: Loading module hook 'hook-encodings.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
3908 INFO: Loading module hook 'hook-pickle.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
5524 INFO: Loading module hook 'hook-heapq.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
6387 INFO: Caching module dependency graph...
6450 INFO: Running Analysis Analysis-00.toc
6450 INFO: Looking for Python shared library...
6560 INFO: Using Python shared library: C:\Python311\python311.dll
6560 INFO: Analyzing F:\wslAccess\usdb_syncer\src\usdb_syncer\main.py
7721 INFO: Loading module hook 'hook-charset_normalizer.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
8035 INFO: Loading module hook 'hook-certifi.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
8192 INFO: Loading module hook 'hook-sqlite3.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
8443 INFO: Loading module hook 'hook-lz4.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
8443 INFO: Loading module hook 'hook-Cryptodome.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
8836 INFO: Loading module hook 'hook-platform.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
9008 INFO: Loading module hook 'hook-keyring.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
9385 INFO: Loading module hook 'hook-importlib_metadata.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
9416 INFO: Loading module hook 'hook-PySide6.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
9872 INFO: Loading module hook 'hook-unidecode.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
10390 INFO: Loading module hook 'hook-lxml.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
10735 INFO: Loading module hook 'hook-appdirs.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
10892 INFO: Processing pre-safe import module hook win32com from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
10923 INFO: Processing pre-safe import module hook gi from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-gi.py'.
11441 INFO: Loading module hook 'hook-yt_dlp.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\yt_dlp\\__pyinstaller'...
Adding imports: ['yt_dlp.compat._legacy', 'yt_dlp.compat._deprecated', 'yt_dlp.utils._legacy', 'yt_dlp.utils._deprecated', 'Cryptodome', 'websockets', 'websockets.__main__', 'websockets.auth', 'websockets.client', 'websockets.connection', 'websockets.datastructures', 'websockets.exceptions', 'websockets.extensions', 'websockets.extensions.base', 'websockets.extensions.permessage_deflate', 'websockets.frames', 'websockets.headers', 'websockets.http', 'websockets.http11', 'websockets.imports', 'websockets.legacy', 'websockets.legacy.async_timeout', 'websockets.legacy.auth', 'websockets.legacy.client', 'websockets.legacy.compatibility', 'websockets.legacy.framing', 'websockets.legacy.handshake', 'websockets.legacy.http', 'websockets.legacy.protocol', 'websockets.legacy.server', 'websockets.protocol', 'websockets.server', 'websockets.speedups', 'websockets.streams', 'websockets.sync', 'websockets.sync.client', 'websockets.sync.compatibility', 'websockets.sync.connection', 'websockets.sync.messages', 'websockets.sync.server', 'websockets.sync.utils', 'websockets.typing', 'websockets.uri', 'websockets.utils', 'websockets.version', 'mutagen', 'brotli', 'certifi']
11739 INFO: Loading module hook 'hook-xml.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
11775 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
12100 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
12979 INFO: Loading module hook 'hook-websockets.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
20210 INFO: Loading module hook 'hook-PIL.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
20273 INFO: Loading module hook 'hook-PIL.Image.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
20713 INFO: Loading module hook 'hook-packaging.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
20744 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
F:\wslAccess\usdb_syncer\.venv\Lib\site-packages\pdfme\color.py:233: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if color is '':
21090 INFO: Processing module hooks...
21456 INFO: Loading module hook 'hook-lxml.etree.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
21648 INFO: Loading module hook 'hook-difflib.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
21868 INFO: Loading module hook 'hook-sysconfig.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
22246 INFO: Loading module hook 'hook-lxml.isoschematron.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
22450 INFO: Loading module hook 'hook-win32ctypes.core.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
22843 INFO: Loading module hook 'hook-pkg_resources.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
23883 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
24274 INFO: Loading module hook 'hook-platformdirs.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
24359 INFO: Loading module hook 'hook-PySide6.QtCore.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
24774 INFO: Loading module hook 'hook-PySide6.QtGui.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
25687 INFO: Loading module hook 'hook-PySide6.QtNetwork.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
26249 INFO: Loading module hook 'hook-PySide6.QtWidgets.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
26754 INFO: Loading module hook 'hook-lxml.objectify.py' from 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
29012 INFO: Looking for ctypes DLLs
29211 INFO: Analyzing run-time hooks ...
29218 INFO: Including run-time hook 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
29219 INFO: Including run-time hook 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
29221 INFO: Including run-time hook 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
29223 INFO: Including run-time hook 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
29227 INFO: Including run-time hook 'F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pyside6.py'
29249 INFO: Looking for dynamic libraries
30036 INFO: Extra DLL search directories (AddDllDirectory): ['F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\shiboken6']
30037 INFO: Extra DLL search directories (PATH): ['F:\\wslAccess\\usdb_syncer\\.venv\\Lib\\site-packages\\PySide6']
32356 INFO: Warnings written to F:\wslAccess\usdb_syncer\build\USDBSyncer\warn-USDBSyncer.txt
32529 INFO: Graph cross-reference written to F:\wslAccess\usdb_syncer\build\USDBSyncer\xref-USDBSyncer.html
32668 INFO: checking PYZ
32669 INFO: Building PYZ because PYZ-00.toc is non existent
32669 INFO: Building PYZ (ZlibArchive) F:\wslAccess\usdb_syncer\build\USDBSyncer\PYZ-00.pyz
34265 INFO: Building PYZ (ZlibArchive) F:\wslAccess\usdb_syncer\build\USDBSyncer\PYZ-00.pyz completed successfully.
34332 INFO: checking PKG
34333 INFO: Building PKG because PKG-00.toc is non existent
34333 INFO: Building PKG (CArchive) USDBSyncer.pkg
45549 INFO: Building PKG (CArchive) USDBSyncer.pkg completed successfully.
45552 INFO: Bootloader F:\wslAccess\usdb_syncer\.venv\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
45552 INFO: checking EXE
45552 INFO: Building EXE because EXE-00.toc is non existent
45552 INFO: Building EXE from EXE-00.toc
45552 INFO: Copying bootloader EXE to F:\wslAccess\usdb_syncer\dist\USDBSyncer.exe
45792 INFO: Copying icon to EXE
45905 INFO: Copying 0 resources to EXE
45905 INFO: Embedding manifest in EXE
46008 INFO: Appending PKG archive to EXE
46041 INFO: Fixing EXE headers
46704 INFO: Building EXE from EXE-00.toc completed successfully.
PS F:\wslAccess\usdb_syncer> .\dist\USDBSyncer.exe
ERROR:root:Uncaught exception:
    Traceback (most recent call last):
      File "usdb_syncer\main.py", line 66, in <module>
      File "usdb_syncer\main.py", line 56, in cli_entry
      File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
      File "usdb_syncer\gui\mw.py", line 22, in <module>
      File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
      File "usdb_syncer\gui\about_dialog.py", line 7, in <module>
    ModuleNotFoundError: No module named 'usdb_syncer.gui.forms'
[26788] Failed to execute script 'main' due to unhandled exception!

**Comment by mjhalwa** [comment]
I guess the problem is in your steps:

> ```
> python -m pip install pipenv --user
> pip install pyinstaller
> python -m pipenv sync --dev
> pyinstaller --name "USDBSyncer" --onefile src/usdb_syncer/main.py
> ```

1. `python -m pip install pipenv --user` :heavy_check_mark: installs pipe v on your pc for whatever python version you call with python
2. `pip install pyinstaller` :x: installes pyinstaller to the python where you call pip.exe from. You rather want
    1. `python -m pipenv sync --dev` first to create the local environment, then
    2. `pipenv shell` to enter the created environment
    3. `pip install pyinstaller` to install pyinstaller to your created environment so that you have dependencies and pyinstaller available in the same environment
3. `python -m src.tools.generate_pyside_files` - this step seems missing in our installation instructions, as it is part of the release process in the github action. It is necessary to build the ui forms (that seem to be missing indicated by your error). But you have to call this with the src directory added to the `PYTHONPATH`
4. `pyinstaller --name "USDBSyncer" --onefile src/usdb_syncer/main.py` which you now call inside the environment

so it should actually be

```
python -m pip install pipenv --user
python -m pipenv sync --dev
pipenv shell
pip install pyinstaller
$env:PYTHONPATH = "$env:PYTHONPATH;.\src"
python -m src.tools.generate_pyside_files
pyinstaller --name "USDBSyncer" --onefile src/usdb_syncer/main.py
```
I can verify later on

**Comment by RumovZ** [comment]
Indeed, the docs for building are not well maintained. That's because we almost only build as part of the automatic release workflow.
What's your use case? Are you aware that there is no need to build anything if you just want to run the app?

**Comment by rogerGunis** [comment]
Hi,
thank you for your patience. Additionally I did a change in the pyenv.cfg in .venv director. i did:
 include-system-site-packages = true

home = C:\Python311
implementation = CPython
version_info = 3.11.3.final.0
virtualenv = 20.24.6
include-system-site-packages = true
base-prefix = C:\Python311
base-exec-prefix = C:\Python311
base-executable = C:\Python311\python.exe
prompt = usdb_syncer

unfortunately problem persist.

Regards
Roger

**Comment by rogerGunis** [comment]
finally I downloaded the binary for windows and I have to say - this project is really great.  Thank you for your work. I've searched for this a long time. :-)

**Comment by mjhalwa** [comment]
leaving aside the installation of `pipenv`:

- :x: I can reproduce `ModuleNotFoundError: No module named 'usdb_syncer.gui.forms'` with

  ```
  python -m pipenv sync --dev
  pipenv shell
  pyinstaller --name "USDBSyncer" --onefile src/usdb_syncer/main.py
  .\dist\USDBSyncer.exe
  ```

- ✅  and this installs and starts the GUI as expected

  ```
  python -m pipenv sync --dev
  pipenv shell
  $env:PYTHONPATH = "$env:PYTHONPATH;.\src"
  python -m src.tools.generate_pyside_files
  pyinstaller --name "USDBSyncer" --onefile src/usdb_syncer/main.py
  .\dist\USDBSyncer.exe
  ```

**Comment by mjhalwa** [comment]
> finally I downloaded the binary for windows and I have to say - this project is really great. Thank you for your work. I've searched for this a long time. :-)

I am glad to can help :). If you still are interested in building yourself, please checkout my instructions above these should work now

**Comment by rogerGunis** [comment]
I will close this issue. At last (on wsl) I had an additional problem

    Traceback (most recent call last):
      File "usdb_syncer/main.py", line 66, in <module>
      File "usdb_syncer/main.py", line 61, in cli_entry
      File "usdb_syncer/gui/mw.py", line 335, in main
      File "usdb_syncer/gui/mw.py", line 344, in _load_main_window
      File "usdb_syncer/song_list_fetcher.py", line 20, in get_all_song_data
      File "usdb_syncer/song_list_fetcher.py", line 46, in get_available_songs
      File "usdb_syncer/usdb_scraper.py", line 341, in get_usdb_available_songs
      File "usdb_syncer/usdb_scraper.py", line 238, in get_usdb_page
      File "usdb_syncer/usdb_scraper.py", line 229, in page
      File "usdb_syncer/usdb_scraper.py", line 84, in session
      File "usdb_syncer/usdb_scraper.py", line 49, in establish_usdb_login
      File "usdb_syncer/settings.py", line 30, in get_usdb_auth
      File "keyring/core.py", line 56, in get_password
      File "keyring/backends/fail.py", line 28, in get_password
    keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.


I fixed it with

export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring

after that the UI appeared.

Thank you very much - closing this issue
