### ISSUE TITLE
Normalize audio with ffmpeg

### ISSUE THREAD

**Issue by fahrnertim** [bohning/usdb_syncer#194]
I am on 0.3.0 for Windows. I downloaded a bunch of songs and realized, that some songs are pretty low on volume.
I guess its a problem with the source video.
Maybe the ffmpeg converting process could also do some normalization to the audio files like described in the following wiki article:
https://trac.ffmpeg.org/wiki/AudioVolume

**Comment by bohning** [comment]
Preferences --> Normalize ;-)

**Comment by fahrnertim** [comment]
Sorry my bad :)
Great tool :) have 3 vegan pizzas for the work :)
