### ISSUE TITLE
Insufficient column-width for fixed-length columns on Linux

### ISSUE THREAD

**Issue by DeinAlptraum** [bohning/usdb_syncer#197]
The ID column is not wide enough to show the entire song ID, and since the width is fixed, I cannot adjust this to fit either. See screenshot:
![no_id](https://github.com/bohning/usdb_syncer/assets/51118500/5ffef0a4-6e4e-4232-ab65-526431a2dffe)

After restarting just now, the same problem appeared in the Rating and Golden Notes columns:
![Screenshot_20231212_192917](https://github.com/bohning/usdb_syncer/assets/51118500/ffe5a1d7-e25d-4410-ae09-44a24fef268a)

I tested this on an ArchLinux KDE system with Noto Sans 10pt as the system font. Changing the font size to 9pt fixes the Rating and Golden Notes columns, and setting it to 8pt also fixes the ID column.

**Comment by barbeque-squared** [comment]
![2023-12-09-100401_141x316_scrot](https://github.com/bohning/usdb_syncer/assets/5775429/90e3f28b-d41b-41f9-8765-e19e76e34c87)
The ID and Golden Notes columns are wide enough for me, Rating one is a little bit too small though.
This is on Archlinux XFCE, system font DejaVu Sans Book 10, DPI 80. Not sure if theme can also be a factor in this, but I doubt that DeinAlptraum runs my exact custom theme.

I'm assuming Alptraum is running either default (=96) or at least some higher DPI than me. Weirdly enough it looks like the column width are _exactly_ the same amount of pixels? This should be pretty easy to verify by using like 200 DPI but idk how to apply it to just one application (I don't want to change it through Xfce settings, it potentially messes up too much other stuff)

**Comment by bohning** [comment]
The thing is, it already takes fontMetrics and devicePixelRatio into account:

**Comment by DeinAlptraum** [comment]
> ![2023-12-09-100401_141x316_scrot](https://github.com/bohning/usdb_syncer/assets/5775429/90e3f28b-d41b-41f9-8765-e19e76e34c87)
> I'm assuming Alptraum is running either default (=96) or at least some higher DPI than me

96 is correct
