### ISSUE TITLE
No Menubar in KDE Plasma 5.27.7

### ISSUE THREAD

**Issue by Juli0q** [bohning/usdb_syncer#198]
I am using Global Menu in KDE. And the menu options are not visible in Global Menu. Even when removing the Global Menu, the in application menu bar is not visible.

With Global Menu removed:
![With global Menu removed](https://github.com/bohning/usdb_syncer/assets/57097234/6f9c5842-ed1b-4cfb-9f24-1d9cf1b9ff8e)

Using Global Menu:
![With Global Menu](https://github.com/bohning/usdb_syncer/assets/57097234/ed267855-bfea-4bc1-bc44-3f9d19c4a657)

Thx

**Comment by RumovZ** [comment]
None of the main developers will be able to fix this, as we're all on macOS or Windows. But if you find a fix, please open a PR.

**Comment by RumovZ** [comment]
Thanks for letting us know! We can add it to the troubleshooting section.
