### ISSUE TITLE
Audio normalization

### ISSUE THREAD

**Issue by bohning** [bohning/usdb_syncer#21]
One problem I have often encountered is that the loudness is different in each song, so maybe usdb_dl can alleviate the problem by performing some kind of audio normalization on the song collection.

Maybe this could be helpful:

- https://wiki.tnonline.net/w/Blog/Audio_normalization_with_FFmpeg
- https://github.com/slhck/ffmpeg-normalize/
- https://github.com/marcosdotme/auto-2pass-loudnorm
- https://github.com/chaudum/rgain3
- https://github.com/jiaaro/pydub
- https://stackoverflow.com/questions/42492246/how-to-normalize-the-volume-of-an-audio-file-in-python
- https://bbs.archlinux.org/viewtopic.php?id=269966
- https://github.com/Moonbase59/loudgain
- https://github.com/dgilman/aacgain
- https://github.com/slhck/ffmpeg-normalize
- https://github.com/yt-dlp/yt-dlp/issues/3409

**Comment by mjhalwa** [comment]
Fot future debugging/testing (based on the currently siggested youtube-link):

- a __quiet__ song: http://usdb.animux.de/index.php?link=detail&id=3453
- a __variable loudness__ song starting loud, but having several quiet parts as well: http://usdb.animux.de/index.php?link=detail&id=5846
- a __loud__ song: http://usdb.animux.de/index.php?link=detail&id=19086

**Comment by RumovZ** [comment]
Closed in #88.
