### ISSUE TITLE
Add Opus sound format to grab from Youtube

### ISSUE THREAD

**Issue by Rumbah2** [bohning/usdb_syncer#214]
Hi,

I'd like to suggest support for Opus. It's a free sound format that Youtube directly supports and should be pretty transparent at Youtube bitrates (better than ogg vorbis).

It is at least supported by USDX and Vocaluxe nightly.

**Comment by bohning** [comment]
>  that Youtube directly supports
What do you mean by that? AFAIK m4a is always available (hence the Syncer default, no conversion involved, fast), webm as well (but support in karaoke softwares is limited), mp3 is not natively available, thus always involves (time-consuming) post-processing. What would be the benefit of supporting opus?

**Comment by Rumbah2** [comment]
Sorry for the late response. I think Opus is the highest quality option on Youtube. As far as i know Google used FAAC for aac on youtube and that encoder is not that good. The free Opus encoder is pretty good at 128 kbit/s so I thout that was a good choice for singing :) .

**Comment by bohning** [comment]
It's already in the `support_opus`branch, if you want to test it.

**Comment by Rumbah2** [comment]
Sorry, I don't really have the knowledge to get the branch running at my computer. If you have a compiled bit I sure would test it.
