### ISSUE TITLE
Indexing existing song directory hangs

### ISSUE THREAD

**Issue by g3n35i5** [bohning/usdb_syncer#244]
**Platform**

macOS 14.4.1 (Darwin)
Python 3.11.9
External SSD (USB 3.2), exFAT formatted
`usdb_syncer` version: 0.5.0 version from GitHub as well as the latest dev version (locally started in venv, commit: 5053d29

**Steps to reproduce**

- Download the entire Database to an external SSD with `usdb_syncer`
- Reset `usdb_syncer` (Settings, ...)
- Open `usdb_syncer` again and select song directory on external drive
- Watch `usdb_syncer` starting to index the song directory, after approx. 15 seconds no more console  output, the process is stuck (I let it run for 12 hours to ensure that this is not a display bug)

**Additional information**

I did the same on my Linux machine, there everything works fine.

**Comment by bohning** [comment]
Interesting. I have a pretty similar setup (SDXC in card slot, exFAT formatted), but while I don't have the problem you mentioned, I see other problems, e.g. redownloading a song that leads to a renaming of the song folder (e.g. artist or title changed slightly) will show "failed" although everything worked, same for songs that contain special characters (without change in artist/title).
