### ISSUE TITLE
Problems with directory names, special characters and exFAT?

### ISSUE THREAD

**Issue by bohning** [bohning/usdb_syncer#245]
With my collection on an exFAT formatted SDXC card, I have the problem that redownloading a song that contains special characters leads to a redownload into a new folder instead of using the existing folder (and skipping the song if the resources haven't changed).

Example:
`Artist - Title with special character` directory already exists. Upon redownload, a second directory `Artist - Title with special character (1)` is created and the entire song is re-downloaded (so I end up having it twice). Thus, skipping existing songs for unchanged resources fails.

Not sure if this is Mac related or exFAT related or Mac+exFAT related, so would be interested if anyone can reproduce this (on Mac and on other platforms using an exFAT formatted external device).

I assume this has to do with Unicode normalization of directory names, googled a bit about it, but couldn't find anything specific to exFAT, but maybe it's related to Apple's HFS.

https://community.roonlabs.com/t/rock-having-problems-with-special-characters-german-aou-in-folder-names/119702
https://handbook.datalad.org/en/0.17/intro/filenaming.html
https://en.wikipedia.org/wiki/Filename
https://superuser.com/questions/999232/unicode-filenames-in-windows-vs-mac-os-x
https://stackoverflow.com/questions/74960030/rename-file-impossible-because-of-special-characters-in-filename

From the 4th link (superuser.com), one of the commenters states:

> **Windows uses UTF-16**. Most codepoints are encoded in two bytes. Codepoints outside the BMP (Basic Multilingual Plane) are encoding in a "surrogate pair" that takes four bytes. **Windows does not normalize filenames using any Unicode Normalization Form**.

> This means you could have two filenames that look identical with one using a precomposed "é" consisting of a single codepoint and the other using a regular ASCII "e" followed by a Unicode combining acute accent, thus two codepoints.

> **OS X uses UTF-8**. Codepoints are encoded using between one and five bytes. **OS X uses Unicode NFD (Normalization Form Canonical Decomposition)**.

> This means that when a Unicode character such as "é" is used in a filename it will always be normalized by the system into a regular ASCII "e" followed by a Unicode combining acute accent, and will always take two codepoints.

> In fact OS X uses the spec of Unicode NFD from either Unicode version 2.1 or 3.2, depending on the version of OS X.

The comment includes a link to Technical Note TN1150 about HFS details that is only available through the [wayback machine](https://web.archive.org/web/20200102075734/http://dubeiko.com/development/FileSystems/HFSPLUS/tn1150.html#UnicodeSubtleties)

**Comment by g3n35i5** [comment]
Today I also realized this. Moreover, I think those directory names can lead to multiple issues (non safe charactes, too long, ...).
Maybe we should consider just to hash the names or something like that. I mean, the song metadata would still be rendered prettily but the directory structure could be more compact and "unix friendly" :)

**Comment by bohning** [comment]
Non-safe characters are handled by `sanitize_filename()`, so they should not be an issue. AFAIK all modern filesystems support UTF8 paths/filenames (and the union of illegal characters on all operating systems are sanitized).

Regarding the path length: AFAIK this is only an issue on standard Windows (with the MAX_PATH limit set), macOS and Linux have much higher limits which should not be a problem.

The problem I see with hashed names is that it is very user unfriendly when working with the song collection on file level.

**Comment by bohning** [comment]
I asked ChatGPT about this: "When saving a file to an external drive with exFAT formatting, are the path and file name Unicode normalized?"

When saving a file to an external drive with exFAT formatting, the handling of Unicode normalization for the path and file name depends on the file system implementation and the operating system. Here's a detailed explanation:

exFAT and Unicode
exFAT (Extended File Allocation Table): exFAT is designed to handle large files and large volumes, making it suitable for external drives. It supports Unicode for file names, which allows for international characters.
Unicode Normalization in exFAT
exFAT Specification: The exFAT specification supports Unicode file names but does not mandate a specific Unicode normalization form (e.g., NFC, NFD). This means that the file system itself does not enforce normalization.
Operating System Behavior
Windows: Windows generally uses the NFC (Normalization Form C) for file names. When you save a file on an exFAT drive from Windows, it will typically normalize file names to NFC.

macOS: macOS uses NFD (Normalization Form D) for HFS+ and APFS file systems. However, for exFAT, macOS does not enforce normalization, and file names may be stored as-is without conversion.

Linux: The behavior on Linux can vary depending on the implementation of the exFAT driver. Generally, the exFAT drivers on Linux do not enforce any particular normalization form.

Practical Implications
File Names and Paths: When you save a file to an exFAT drive, the file name and path will be stored in the Unicode form provided by the operating system. If you create a file on Windows, the name will likely be in NFC. If you create it on macOS, it may not be normalized or could be in NFD, depending on the specific implementation and how the text was handled by the application.

Interoperability: Because exFAT itself does not enforce normalization, file names may appear differently when viewed from different operating systems. For example, a file created on macOS may appear with decomposed characters (NFD) when viewed on Linux, while a file created on Windows may appear with composed characters (NFC).

Summary
exFAT File System: Supports Unicode for file names but does not enforce any specific normalization form.
Windows: Typically normalizes file names to NFC when saving to exFAT.
macOS: Does not enforce normalization for exFAT; file names may be saved as-is.
Linux: Behavior depends on the exFAT driver; generally, does not enforce normalization.
Example: Checking Normalization in Python
You can check the normalization form of a file name using Python:

```
import unicodedata

# Example file name
file_name = "éxample.txt"

# Check if the file name is normalized
is_nfc = unicodedata.is_normalized('NFC', file_name)
is_nfd = unicodedata.is_normalized('NFD', file_name)

print(f"File name is NFC: {is_nfc}")
print(f"File name is NFD: {is_nfd}")
```
This script will help you determine the normalization form of a file name, which can be useful when dealing with files across different operating systems and file systems.

**Comment by bohning** [comment]
So maybe the path and filenames should always be Unicode normalized. Not sure if this is OS-dependent (e.g. NFD for macOS, NFC for Windows, ...) or it could be normalized for all OS (NFD?).

Maybe this helps shedding some light onto it: https://stackoverflow.com/questions/7041013/unicode-normalization-in-windows
