### ISSUE TITLE
Executable refuses to open with: "ValueError: invalid literal for int() with base 10: 'English'"

### ISSUE THREAD

**Issue by SteveW94** [bohning/usdb_syncer#253]
Since todays morning, the previously opening fine executable refused to open with the following log output:

![image](https://github.com/bohning/usdb_syncer/assets/36530889/7ebc03ed-1e8a-4bba-bd2e-55f9ea7462c9)

I am happy to fix it myself if I am doing sth. wrong, but as I did not change something and this happens now, I thought I should open an Issue here.

**Comment by bohning** [comment]
Thanks for reporting the issue. USDB has changed (search results now include genre, year and creator) and the parser code for that song list needs to be adapted accordingly.

**Comment by SteveW94** [comment]
Thanks for the quick response on this :)
