### ISSUE TITLE
Could not find the Qt platform plugin "xcb" in ""

### ISSUE THREAD

**Issue by logon84** [bohning/usdb_syncer#264]
I am getting this error trying to open the latest linux version:

qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

I didn't face this problem with 5.0, until it broke due to the changes in usdb site of course. Some clues?

**Comment by bohning** [comment]
According to [this thread](https://forum.qt.io/topic/93247/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found), you could try
- running it with QT_DEBUG_PLUGINS=1 set
- sudo apt-get install libxcb-xinerama0
and see if that yields something useful / works.

**Comment by logon84** [comment]
> According to [this thread](https://forum.qt.io/topic/93247/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found), you could try
> 
>     * running it with QT_DEBUG_PLUGINS=1 set
> 
>     * sudo apt-get install libxcb-xinerama0
>       and see if that yields something useful / works.

Nothing new in the output after setting QT_DEBUG_PLUGINS=1 or installing libxcb-xinerama0 (it was already installed). I am using Linux Mint 21.3 in case someone experiences also the same.

**Comment by logon84** [comment]
If I create the directory "platforms" next to the USDB syncer executable and copy the file /lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb inside, I get the output:

`logon@logonlap:~/.ultrastardx/songs$ ./USDB_Syncer-0.6.0-Linux 
qt.core.plugin.factoryloader: checking directory path "/home/logon/.ultrastardx/songs/platforms" ...
qt.core.plugin.factoryloader: looking at "/home/logon/.ultrastardx/songs/platforms/libqxcb.so"
qt.core.plugin.loader: Found metadata in lib /home/logon/.ultrastardx/songs/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archlevel": 0,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 331520
}


qt.core.plugin.loader: In /home/logon/.ultrastardx/songs/platforms/libqxcb.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.factoryloader: "The plugin '/home/logon/.ultrastardx/songs/platforms/libqxcb.so' uses incompatible Qt library. (5.15.0) [release]" 
         not a plugin
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
`

**Comment by bohning** [comment]
It uses Qt 6.6 (PySide6) if that is of any help.

**Comment by RumovZ** [comment]
It seems to be an issue with PyInstaller. I've fixed this in [5b4b43f](https://github.com/bohning/usdb_syncer/pull/260/commits/5b4b43f9816af4bd31eb0c486cf3d4d9178a7db0) by pinning an older version. There should be a new release soon.
