### ISSUE TITLE
Flagged with trojan by Bitdefender and VirusTotal

### ISSUE THREAD

**Issue by WilkesIsMoore** [bohning/usdb_syncer#265]
Hi, 

Thanks for making this. I've been excited to try it. However, when downloading the Windows 0.6.0 release build Bitdefender flagged and quarantined the file as containing the Variant.Lazy.560823 trojan. I downloaded the .exe file on my Mac and uploaded it to VirusTotal, which resulted in six vendors flagging it. Here's the link: 

https://www.virustotal.com/gui/file/62d873bcda8e46ad13dc38a182ae25cba86d12aadf99c926517825cb981e3159

As others have not reported issues, I'm wondering if something snuck in during your latest build? Thanks!

**Comment by RumovZ** [comment]
Our package manager pipenv doesn't show any known vulnerabilites. I guess it's a false positive, but we can't really do anything about it.
In the end, every user has to decide for themselves if they find the risk acceptable. Running from source can be an alternative.
