### ISSUE TITLE
Only use/fetch cookies when necessary

### ISSUE THREAD

**Issue by bohning** [bohning/usdb_syncer#28]
Possibly fetching browser cookies adds additional download time when it is not necessary for most of the videos. Maybe a meta-tag (e.g. `age-restricted=true`) could be introduced so that cookies are only fetched for those age-restricted videos.

**Comment by bohning** [comment]
This can be used as a test case:

https://www.youtube.com/watch?v=pvy7BLaggt4
http://usdb.animux.de/index.php?link=detail&id=16397

**Comment by RumovZ** [comment]
Closing this as we now only fetch cookies when creating a session and this optimisation probably wouldn't be noticeable.
