### ISSUE TITLE
Syncer crashes if a user tries to download a song that has been deleted from usdb in the meantime

### ISSUE THREAD

**Issue by bohning** [bohning/usdb_syncer#289]
In `song_table.py` --> `assert song` leads to `AssertionError`.

**Comment by RumovZ** [comment]
I can't reproduce that by inserting a fake song in the DB and then downloading it. The row gets removed correctly. When did you observe this?

**Comment by bohning** [comment]
I'd say rather recently, maybe a week ago. I'll try to reproduce it.

**Comment by bohning** [comment]
I added a new song to USDB, refetched the USDB song list, updated the song table, then deleted the song on USDB and then tried to download it. The row correctly disappears and the log message correctly states `2024-09-21 11:53:05 [ERROR] #29399: Song has been deleted from USDB.`. So I cannot reproduce so I'll close this and will reopen this issue should I encounter it again.
