### ISSUE TITLE
'Check USDB song list' should also fetch new songs (like restarting the syncer)

### ISSUE THREAD

**Issue by bohning** [bohning/usdb_syncer#291]

**Comment by RumovZ** [comment]
Pretty sure it does. It fetches the entire song list after all.

**Comment by bohning** [comment]
![image](https://github.com/user-attachments/assets/73a9856e-3c71-4134-97c7-26a0bfb3a508)
https://usdb.animux.de/index.php?link=detail&id=29398
![image](https://github.com/user-attachments/assets/efc4eb71-70a3-44f0-a3ae-e65a7844e82a)
![image](https://github.com/user-attachments/assets/72ecdc71-64b3-487d-a781-5887552f0ab9)
2024-09-21 11:30:43 [INFO] Fetched 26637 new song(s) from USDB.
![image](https://github.com/user-attachments/assets/b01781b0-5655-4a42-bdf1-5cde34b981d7)
