### ISSUE TITLE
Songs are not properly recognised when searching a local folder

### ISSUE THREAD

**Issue by DennisWilken** [bohning/usdb_syncer#293]
I have been using USDB Syncer 0.5 for a while on a Windows 11 mashine. After I bought a new PC and upgraded to 0.7 the software finds 281 songs after adding the local folder - this seems to be right. However, in the main frame only 40 songs are shown when filtering for downloaded files or sorting for those with a green check mark. 

I have tested song files in different locations (server, synced folder, local) with the same result.

Downloading new songs works fine. Any idea what's wrong here? I could search and download all songs manually into a new folder but would prefer to keep my files. 

[usdb_syncer.log](https://github.com/user-attachments/files/17084804/usdb_syncer.log)

**Comment by RumovZ** [comment]
The 'Find local songs' feature only selects songs you have locally so you can redownload them. The Syncer cannot track files you've downloaded manually.

**Comment by RumovZ** [comment]
> If they all match we can generate the .usdb file If they don't match or partially match we can partially fill the usdb file and show the checkmark for that

I don't understand. Match what?
