### ISSUE TITLE
Write the #VIDEO content from USDB to #LINKS

### ISSUE THREAD

**Issue by Gamerios** [bohning/usdb_syncer#314]
Hello

Anyone or you bohning know how i can set int usdb_syncer i have the source code and can run it with python

Want write from the original USDB TXT file the:

#VIDEO:v=2wkekZpikbY,co=https://m.media-amazon.com/images/I/51XjAPo+HEL.jpg,co-crop=42-0-431-431,bg=2raumwohnung-503a7395adf6f.jpg

And in ready created TXT file from usdb_syncer 

want it like
#LINKS:v=2wkekZpikbY,co=https://m.media-amazon.com/images/I/51XjAPo+HEL.jpg,co-crop=42-0-431-431,bg=2raumwohnung-503a7395adf6f.jpg

in the TXT file then of the Song 
 i tryed in song_loader.py  but after hours not find a way   dont knwo why or how 

thanks

rgrads

**Comment by bohning** [comment]
The next release will support format versions 1.0.0 (#MP3), 1.1.0 (#MP3 and #AUDIO) and 1.2.0 (#AUDIO, #AUDIOURL, #COVERURL, #BACKGROUNDURL and #VIDEOURL) which are the agreed upon new tags to store that information. There will be no support for custom tags (see https://usdx.eu/format/).

**Comment by Gamerios** [comment]
thanks when next release ?    

but how can use USDB Synvcer to only download the Text FIle from USDB ?


As want download more from USDB but only the Text Files without changes   if needed    


or can you set in USDB Synce in settings options that can only download TXT or not remove the #VIDEO:v=2wkekZpikbY,co=https://m.media-amazon.com/images/I/51XjAPo+HEL.jpg,co-crop=42-0-431-431,bg=2raumwohnung-503a7395adf6f.jpg   from the ready file if need like the Original file from USDB  but want download with USDB Syncer   infos ?


hope  you can help thanks

regrads
