### ISSUE TITLE
Add usdb uploader as #CREATOR to final text file (where #CREATOR is not set)

### ISSUE THREAD

**Issue by bohning** [bohning/usdb_syncer#34]
In the vast majority of cases (except where otherwise specified in the comments below the song), the uploader is also the song creator. Many songs are missing the #CREATOR tag, so we could fill the gap and take the uploader’s name for #CREATOR unless #CREATOR is already specified (in the local txt file, not in the .usdb file).

**Comment by mjhalwa** [comment]
mentioned as part of #20
