### ISSUE TITLE
Get rid of "[DUET]" in #TITLE for duets

### ISSUE THREAD

**Issue by bohning** [bohning/usdb_syncer#47]

**Comment by mjhalwa** [comment]
I think there are several problems in just having a single DUET txt version to play (at least i did not figure out how to solve this with usdx alone):

- ["Hakuna Matata"](http://usdb.animux.de/index.php?link=detail&id=18284), for example, is a duet, where both players alternate pretty much along the song. It is awkward to sing this song alone as you only sing half the song, while singing along the song on radio you might probably tend to sing both players
- when watching duets on singstart parties there is often one player not satisfied with his part. Either just having "lalala" parts (see [Circle of life](http://usdb.animux.de/index.php?link=detail&id=5846)) or feeling like his/her track is more difficult to sing or has less golden notes. A fair solution would be if both sing both
- still there are situations where one might want so sing p1 and the other want so sing p2 so duets are without question useful
-  finally there is a problem if you want to sing just player 2 of a song, playing without a player 2. Or if 2 players just want to sing player 2 but not player 1

To fit all possible szernatios i propose:

1) have 2 txt for for duet songs on usdb:
  - 1x labeled as [DUET] with p1 and p2 tracks
  - 1x (optional) labeld as [SOLO] with a handmade mixture of p1 and p2. Note this might not be automated, as sometimes two players sing at the same time or with an overlap and slightly different
2) the syncer creates to additional txts from the [DUET] version as [{{P1}}] and [{{P2}}], replacing players with the actual names, each containing only a single track from p1 or p2

where a resulting download of the syncer is a single directory "Artist - Title" (without any of [DUET], [SOLO], etc) containing 4 txts:

- `Artist - Title [DUET].txt`
- `Artist - Title [SOLO].txt` (if present on usdb)
- `Artist - Title [{{P1}}].txt`
- `Artist - Title [{{P2}}].txt`

What do you think about that?

**Comment by RumovZ** [comment]
I agree on the problem, @mjhalwa. However, I don't think it's best solved by the syncer. Generating several txts complicates things and produces a lot of redundant data to maintain.
Instead, the karaoke softwares should let players choose which parts to sing. I think some already do that, at least partially?
