### ISSUE TITLE
Find a suitable app icon

### ISSUE THREAD

**Issue by bohning** [bohning/usdb_syncer#55]
Maybe a coffee machine would fit - UltraStar Creator has the coffee bean (create individual songs), UltraStar Creator has the coffee cup (manage your song collection), thus the Syncer could be the coffee machine that provides your song collection.

Linkware: https://iconarchive.com/show/office-space-icons-by-visualpharm/coffee-machine-icon.html

**Comment by bohning** [comment]
Does anyone how good ideas or suggestions here?

**Comment by bohning** [comment]
https://icon-icons.com/de/symbol/Kaffee-maker/161223
https://www.flaticon.com/free-icon/coffee-machine_2098336?term=coffee+machine&page=1&position=12&origin=tag&related_id=2098336

**Comment by bohning** [comment]
Currently used: https://www.freepik.com/free-vector/pink-neon-cloud-icon-digital-networking-system_16406257.htm
Attribution: <a href="https://www.freepik.com/free-vector/pink-neon-cloud-icon-digital-networking-system_16406257.htm">Image by rawpixel.com</a> on Freepik

**Comment by DoubleDee73** [comment]
Or you could create an icon via AI? e. g. https://creator.nightcafe.studio/studio
then it's guaranteed, it's unique

**Comment by bohning** [comment]
> Or you could create an icon via AI? e. g. https://creator.nightcafe.studio/studio then it's guaranteed, it's unique

I was already looking for AI generating app icons, but all the good ones seem to cost money sooner or later. Tried your suggestion with little success...
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/1497707/236399983-ab7bbb92-4fbb-409f-809f-3b9ce7b82c0d.png">
