### ISSUE TITLE
Add feature to "subscribe" to artists

### ISSUE THREAD

**Issue by BWagener** [bohning/usdb_syncer#61]
It would be a cool addition if users could manage a list of artists they "subscribe" to.

The program could periodically check for new songs in the database featuring these artists and notify the user or automatically synchronize them.

This feature could be extended to generic search criteria such as language etc.

Let me know what you think!

**Comment by RumovZ** [comment]
Cool idea!
What we need first is a way to incrementally update the song list, though. At the moment, always all available songs are fetched from USDB. That takes quite some time, but makes things easy for now.

**Comment by mjhalwa** [comment]
What about generalizing this idea to a kind-of-wishlist? So check if there are new songs where title or artists fit a certain patter / substring (case insensitive!) and get them suggested on application start.

Users could maintain a list of these patterns / search strings in a sidenav or so. The syncer may indicate if any is found or non. Clicking an item in the search list shows corresponding songs in the main table. The user may select them for download as usual and may checkoff / delete the search item.

**Comment by RumovZ** [comment]
Sounds great! So it's basically like a saved filter.
I don't think it should go in the song directory, though. We can put it in the app data dir, like `C:\Users\$USER\AppData\Local\bohning\usdb_syncer` on Windows.

**Comment by mjhalwa** [comment]
Appdata directory is a good Idea, but may Users rather use UI to modify than the file itself, right? (From my experience as User, I tend not to look into the appdata directories.) - I guess this is probably best anyways. 

 We may then need a backup feature someday, otherwise this file may be easily overlooked when migrating to a new machine

**Comment by RumovZ** [comment]
Yes, most users wouldn't modify JSON data directly. I imagine there'd rather be a button to save the current filters to a file.
A migrating tool may be helpful at some point in the future.

**Comment by RumovZ** [comment]
Closed with #270.
