### ISSUE TITLE
Write development guide

### ISSUE THREAD

**Issue by g3n35i5** [bohning/usdb_syncer#7]
Developing with many persons is challenging if not done right. I'll write a developer guide including VSC settings and a dockerfile so that all developers can work in the same environment.

Relates to #4

**Comment by mjhalwa** [comment]
in order to track the individual progress:

- [ ] dockerfile
- [ ] dev guide

**Comment by randompersona1** [comment]
With poetry, Docker isn't necessary. I also believe that the guide is comprehensive enough at this point to set up new developers.
