### ISSUE TITLE
Malformed comment with Youtube URL seems to cause a playlist download

### ISSUE THREAD

**Issue by BWagener** [bohning/usdb_syncer#70]
I didn't have time to look into this yet but downloading [4965](http://usdb.animux.de/?link=detail&id=4965) causes the syncer to download what looks like a playlist.

The result looks like this:
![image](https://user-images.githubusercontent.com/19321042/210167454-3e9ccdf8-7b75-4d20-9867-1104af3dd34a.png)

**Comment by bohning** [comment]
The key `v=` was missing in the meta tags. That’s why the syncer used the commented URL, which, due to the emoji replacement of usdb, has a space in it (after the `=`), so yt-dlp got `https://www.youtube.com/watch?v=` as URL and then just downloads arbitrary videos. It’s fixed now =)
