### ISSUE TITLE
exchange format for a song list

### ISSUE THREAD

**Issue by mjhalwa** [bohning/usdb_syncer#71]
Currently a user selects songs for download in the UI. I want to propose an exchange format for a list of songs:

- a specific file in a song folder might be recognized as a song collection
- the file might list an array of song ids (USDB ids)
- if the syncer recognizes this file on startup it beginns to download all ids from the file (if not already in the current song folder
- the syncer allows to export this file from the local songs
- the syncer allows to export this file from a selected list of songs
- the file should probably not have the extension txt, as this extension is recognized by the Game Applications (instead use JSON?)

This might be particularly useful for the following szenarios:

- if coming from a different software / approach to collect songs
- sending over a list of songs to a friend
- create a song list for certain events to be loaded on demand (might allow to create more complex "Editions" then the `#EDITION` tag does)
- continous extension of current local songs (i'd like to collect USDB urls on my phone and then download all songs some day i start the syncer to work them through in order to check their quality and complete them)
- backup of the local file list

**Comment by RumovZ** [comment]
Great idea!
Can we reuse the format for https://github.com/bohning/usdb_syncer/issues/61#issuecomment-1368113611? If this issue is just about a list of ids, we don't need JSON and could just use CSV, (In fact, it's even simpler than CSV, because we only have a single row.)
Again, I wouldn't put this in the song folder. Maybe we can add an import/export feature?
If we automatically process all id lists in a certain folder, this would probably increase startup time, even if all songs are already downloaded.

**Comment by mjhalwa** [comment]
Personally CSV feels more like other kind of data, but I agree it does not have to be json, at the moment its just a single column.

But we might extend this format in the future to contain extra infos for each id. E.g. we may add the progress of the song in terms of songcheck, all required files abailable, ready to play, what needs to be done etc. Or we add  custom set of Editions / Labels / Tags for whatever reason.

But i am also fine with just a plain csv for the moment.

**Comment by RumovZ** [comment]
Yeah, the app data dir is not a good fit here. What I meant was, you have an import tool that lets you pick a file from anywhere. There's no reason such a file should be at any specific location.

**Comment by mjhalwa** [comment]
oh yes true... So probably two Actions in a "File" Menu for "Import" and "Export" (probably also "Export All My Songs") where both open a file selector and the second exports all selected files.

**Comment by mjhalwa** [comment]
fixed by fdc6ad5
