### ISSUE TITLE
redirecting bg URL in Meta-Tag saves invalid jpg with html content, does not log properly and throws exception

### ISSUE THREAD

**Issue by mjhalwa** [bohning/usdb_syncer#73]
## Problem

if the `bg` Tag contains a URL that is redirecting to a different page, the generated background image instead contains the html content of the redirected page. In the current scenario the target URL is not an image itself but a webpage.

The syncer UI does not log anything about the image. The console output shows a Python traceback -> exception seems not to be caught.

## Expected

Either the background image is downloaded or the syncers log should indicate that the url is invalid (probably also how it is invalid - in this case leading to a webpage not an image). If the background image cannot be loaded a file should not be generated.

## Details:

**WARNING: Following the stated problematic URL in `bg` redirects leads to PORNOGRAPHIC webpage!**

Currently there are 3 songs for "Disney's Eiskönigin - Lass jetzt los"

- http://usdb.animux.de/index.php?link=detail&id=17227
- http://usdb.animux.de/index.php?link=detail&id=18408
- http://usdb.animux.de/index.php?link=detail&id=18719

which have the same meta-tag:

``` conf
#VIDEO:v=Jc10TXOh-yM,co=static.universal-music.de/asset_new/480408/195/view/Die-Eiskoenigin---Voellig-unverfroren--Deutscher-Original-Soundtrack.jpg,bg=motaen.com/upload/wallpapers/source/2014/01/26/20/04/39018/tNXdnd2Xtx.jpg 
```

The complete log from within the syncer (syncer start and only download of 17227) is:

``` log
2023-01-06 22:12:16 [INFO] Application successfully loaded.
2023-01-06 22:12:38 [INFO] #17227: Found 'Disney’s Die Eiskönigin - Lass jetzt los' on  USDB
2023-01-06 22:13:04 [INFO] #17227: Success! Downloaded audio.
2023-01-06 22:13:19 [INFO] #17227: Success! Downloaded video.
2023-01-06 22:13:20 [INFO] #17227: Success! Downloaded cover.
```

end of log on the console:

``` log
#...
2023-01-06 22:13:19 [INFO] #17227: Success! Downloaded video.
2023-01-06 22:13:20 [INFO] #17227: Success! Downloaded cover.
Traceback (most recent call last):
  File "{PROJECTPATH}\usdb_syncer\src\usdb_syncer\song_loader.py", line 157, in run
    _maybe_download_background(ctx)
  File "{PROJECTPATH}\usdb_syncer\src\usdb_syncer\song_loader.py", line 248, in _maybe_download_background
    if filename := download_and_process_image(
  File "{PROJECTPATH}\usdb_syncer\src\usdb_syncer\resource_dl.py", line 163, in download_and_process_image
    _process_image(meta_tags, max_width, path)
  File "{PROJECTPATH}\usdb_syncer\src\usdb_syncer\resource_dl.py", line 188, in _process_image
    with Image.open(path).convert("RGB") as image:
  File "{PROJECTPATH}\usdb_syncer\venv\lib\site-packages\PIL\Image.py", line 3186, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '{PROJECTPATH}\\usdb_syncer\\songs\\Disney’s Die Eiskönigin - Lass jetzt los\\Disney’s Die Eiskönigin - Lass jetzt los [BG].jpg'
```

Note: I replace the path to the syncer directory on my machine with `{PROJECTPATH}`

The __non-empty__ stored image `Disney’s Die Eiskönigin - Lass jetzt los [BG].jpg` actually contains HTML content and is (surprise) __not a valid JPG__. When opening the URL in the webbrowser a page on a different (**pornographic!!**) domain `https://erowall.com/` is opened that seems to match the content of the jpg.

I checked with [Postman](https://www.postman.com/) without following redirects how HTTP Response from the initial `GET`-Request to the `bg`-URL looks like:

headers:

- Status: [`302 Found`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302)

  > The HyperText Transfer Protocol (HTTP) `302 Found` redirect status response code indicates that the resource requested has been temporarily moved to the URL given by the [Location](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location) header. A browser redirects to this page but search engines don't update their links to the resource (in 'SEO-speak', it is said that the 'link-juice' is not sent to the new URL).

- Server: `nginx`
- Date: `Fri, 06 Jan 2023 21:17:19 GMT`
- Content-Type: `text/html; charset=iso-8859-1`
- Content-Length. `204`
- Connection: `keep-alive`
- Keep-Alive: `timeout=60`
- Location: `https://erowall.com/`

body:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>

<head>
	<title>302 Found</title>
</head>

<body>
	<h1>Found</h1>
	<p>The document has moved <a href="https://erowall.com/">here</a>.</p>
</body>

</html>
```

**Comment by RumovZ** [comment]
Closed in 098988c13c63520c35000c37a287b1cf9598ec52.
