### ISSUE TITLE
Reencoding videos doesn't work (anymore?)

### ISSUE THREAD

**Issue by g3n35i5** [bohning/usdb_syncer#86]
The `Reencode Video` toggle in the settings doesn't seem to have any effect. I'm pretty sure this feature worked in the past :laughing:

**Comment by RumovZ** [comment]
See #15.
We should either remove the toggle or (re)implement reencoding.
In the latter case, we should also decide if we want to support trimming (using #START and #END) and cropping (crop tag has also been removed for now). Of course, these decesions may be deferred.
