### ISSUE TITLE
Do not immediately trigger search

### ISSUE THREAD

**Issue by DoubleDee73** [bohning/usdb_syncer#89]
It would be nice, if the search did not start immediately, but would rather wait until the user has typed in a couple of characters or hit the Enter key

**Comment by RumovZ** [comment]
That's actually a deliberate feature. Why is it a the problem?

**Comment by DoubleDee73** [comment]
sorry, didn't notice the comment.

In an earlier version, every keystroke took a couple of seconds for the filter to take effect. This seems to have resolved in later versions now.
